// packages/angular/line/src/line.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  PLATFORM_ID,
  SimpleChanges,
  ViewChild,
} from "@angular/core";
import { isPlatformBrowser } from "@angular/common";
import type { DeepPartial, Viewport } from "@sixtyfold/core";
import {
  LineChart,
  type LineAppearanceOptions,
  type LineChartOptions,
  type LineChartStats,
  type LineDataUpdateOptions,
  type SeriesVisibilityChangeEvent,
} from "@sixtyfold/line";
import { createStatsEmitter, hasViewport, installLineData, type LineData } from "./shared";

export type CanvasAttributes = Record<string, string | number | boolean | null | undefined>;

const MANAGED_CANVAS_ATTRIBUTES = new Set([
  "aria-label",
  "aria-describedby",
  "class",
  "height",
  "role",
  "style",
  "tabindex",
  "width",
]);

/** Standalone Angular component hosting a Sixtyfold line chart. */
@Component({
  selector: "sixtyfold-line-chart",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<canvas
    #canvas
    [class]="canvasClass"
    [attr.aria-label]="resolvedAriaLabel"
    [attr.aria-describedby]="ariaDescribedBy"
    [attr.role]="resolvedCanvasRole"
    [attr.tabindex]="resolvedCanvasTabIndex"
  ></canvas>`,
  styles: [
    `
      :host {
        display: block;
        min-width: 0;
        min-height: 0;
      }
      canvas {
        display: block;
        width: 100%;
        height: 100%;
      }
    `,
  ],
})
export class SixtyfoldLineChartComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild("canvas", { static: true }) private canvasRef?: ElementRef<HTMLCanvasElement>;

  @Input() options: LineChartOptions = {};
  @Input() data?: LineData;
  @Input() dataUpdateOptions?: LineDataUpdateOptions;
  @Input() appearance?: DeepPartial<LineAppearanceOptions>;
  @Input() viewport?: Partial<Viewport>;
  /** Leave undefined to inherit the chart's configured `animated` default. */
  @Input() viewportAnimated?: boolean;
  @Input() statsIntervalMs?: number;
  @Input() canvasClass = "";
  @Input() ariaLabel?: string;
  @Input() ariaDescribedBy?: string;
  @Input() canvasRole?: string;
  @Input() canvasTabIndex?: number;
  /** Additional attributes for the canvas host. Chart-owned accessibility,
   *  class, style, and bitmap-size attributes remain controlled above. */
  @Input() canvasAttributes?: CanvasAttributes;

  @Output() readonly chartReady = new EventEmitter<LineChart>();
  /** Reports construction, renderer, and overlay-image failures. */
  @Output() readonly chartError = new EventEmitter<unknown>();
  @Output() readonly stats = createStatsEmitter<LineChartStats>(() => this.syncStatsCallback());
  @Output() readonly seriesVisibilityChange = new EventEmitter<SeriesVisibilityChangeEvent>();

  chart: LineChart | null = null;
  private ready = false;
  private readyNotified = false;
  private rendererFailed = false;
  private destroyed = false;
  private appliedData?: LineData;
  private appliedAppearance?: DeepPartial<LineAppearanceOptions>;
  private appliedViewport?: Partial<Viewport>;
  private statsEnabled?: boolean;
  private statsInterval?: number;
  private reportedRendererError: unknown;
  private readonly appliedCanvasAttributes = new Set<string>();

  private readonly platformId = inject(PLATFORM_ID);

  get resolvedAriaLabel(): string {
    return this.ariaLabel ?? (this.options.interactive === false ? "Chart" : "Interactive chart");
  }

  get resolvedCanvasRole(): string {
    return this.canvasRole ?? (this.options.interactive === false ? "img" : "application");
  }

  get resolvedCanvasTabIndex(): number | null {
    return this.canvasTabIndex ?? (this.options.interactive === false ? null : 0);
  }

  ngAfterViewInit(): void {
    this.syncCanvasAttributes();
    if (isPlatformBrowser(this.platformId)) this.mount();
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.syncCanvasAttributes();
    this.syncStatsCallback();
    if (!this.ready) return;
    this.applyReactiveInputs();
  }

  private syncCanvasAttributes(): void {
    const canvas = this.canvasRef?.nativeElement;
    if (!canvas) return;
    const next = this.canvasAttributes ?? {};
    for (const name of this.appliedCanvasAttributes) {
      if (!(name in next) || next[name] == null || next[name] === false) {
        canvas.removeAttribute(name);
        this.appliedCanvasAttributes.delete(name);
      }
    }
    for (const [rawName, value] of Object.entries(next)) {
      const name = rawName.toLowerCase();
      if (MANAGED_CANVAS_ATTRIBUTES.has(name) || value == null || value === false) continue;
      canvas.setAttribute(rawName, value === true ? "" : String(value));
      this.appliedCanvasAttributes.add(rawName);
    }
  }

  private mount(): void {
    const canvas = this.canvasRef?.nativeElement;
    if (!canvas || this.destroyed || this.chart) return;
    let chart: LineChart;
    try {
      chart = new LineChart(canvas, this.options);
    } catch (error) {
      if (!this.destroyed) this.chartError.emit(error);
      return;
    }
    this.chart = chart;
    chart.setRendererErrorCallback((error) => {
      this.rendererFailed = true;
      this.reportedRendererError = error;
      if (!this.destroyed) this.chartError.emit(error);
    });
    chart.setOverlayErrorCallback((error) => {
      if (!this.destroyed) this.chartError.emit(error);
    });
    this.syncStatsCallback();
    chart.setSeriesVisibilityCallback((event) => this.seriesVisibilityChange.emit(event));
    void chart
      .initialize()
      .then(() => {
        if (this.destroyed || this.chart !== chart) return;
        this.ready = true;
        this.applyReactiveInputs();
      })
      .catch((error) => {
        if (!this.destroyed && error !== this.reportedRendererError) {
          this.chartError.emit(error);
        }
      });
  }

  /** Collecting stats costs renderer work, so it stays off until something
   *  subscribes to the `stats` output, and is re-sent only when it changes. */
  private syncStatsCallback(): void {
    const chart = this.chart;
    if (!chart || this.destroyed) return;
    const enabled = this.stats.observed;
    if (enabled === this.statsEnabled && this.statsIntervalMs === this.statsInterval) return;
    this.statsEnabled = enabled;
    this.statsInterval = this.statsIntervalMs;
    chart.setStatsCallback(enabled ? (value) => this.stats.emit(value) : null, {
      intervalMs: this.statsIntervalMs,
    });
  }

  /** Installs every reactive input in a single engine update. Each dataset
   *  object is applied at most once. Worker mode transfers its buffers;
   *  identity tracking also prevents duplicate installs in main-thread mode. */
  private applyReactiveInputs(): void {
    const chart = this.chart;
    if (!chart || !this.ready || this.destroyed || this.rendererFailed) return;
    try {
      chart.batch(() => {
        if (this.data && this.data !== this.appliedData) {
          installLineData(chart, this.data, this.dataUpdateOptions);
          this.appliedData = this.data;
        }
        if (this.appearance && this.appearance !== this.appliedAppearance) {
          chart.updateAppearance(this.appearance);
          this.appliedAppearance = this.appearance;
        }
        if (hasViewport(this.viewport) && this.viewport !== this.appliedViewport) {
          chart.setViewport(this.viewport, { animated: this.viewportAnimated });
          this.appliedViewport = this.viewport;
        }
      });
    } catch (error) {
      if (!this.destroyed && error !== this.reportedRendererError) this.chartError.emit(error);
      return;
    }
    if (!this.destroyed && !this.rendererFailed && this.chart === chart && !this.readyNotified) {
      this.readyNotified = true;
      this.chartReady.emit(chart);
    }
  }

  ngOnDestroy(): void {
    this.destroyed = true;
    this.ready = false;
    this.chart?.destroy();
    this.chart = null;
  }
}

// packages/svelte/src/line.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { DeepPartial, Viewport } from "@sixtyfold/core";
  import {
    LineChart,
    type LineAppearanceOptions,
    type LineChartOptions,
    type LineChartStats,
    type LineDataUpdateOptions,
    type SeriesVisibilityChangeEvent,
  } from "@sixtyfold/line";
  import { hasViewport, installLineData, type LineData } from "./shared.js";

  /** Construction-time options. Remount the component to replace them. */
  export let options: LineChartOptions = {};
  /**
   * One-shot chart data. Assign a new object for each update. Worker mode
   * transfers and detaches its buffers; main-thread mode retains references.
   */
  export let data: LineData | undefined = undefined;
  export let dataUpdateOptions: LineDataUpdateOptions | undefined = undefined;
  export let appearance: DeepPartial<LineAppearanceOptions> | undefined = undefined;
  export let viewport: Partial<Viewport> | undefined = undefined;
  /** Leave undefined to inherit the chart's configured `animated` default. */
  export let viewportAnimated: boolean | undefined = undefined;
  export let statsIntervalMs: number | undefined = undefined;
  export let onReady: ((chart: LineChart) => void) | undefined = undefined;
  /** Reports construction, renderer, and overlay-image failures. */
  export let onError: ((error: unknown) => void) | undefined = undefined;
  export let onStats: ((stats: LineChartStats) => void) | undefined = undefined;
  export let onSeriesVisibilityChange: ((event: SeriesVisibilityChangeEvent) => void) | undefined =
    undefined;
  export let canvasClass = "";
  export let canvasStyle = "";
  export let ariaLabel: string | undefined = undefined;
  export let ariaDescribedBy: string | undefined = undefined;
  export let canvasRole: string | undefined = undefined;
  export let canvasTabIndex: number | undefined = undefined;
  /** Bindable access to the mounted imperative chart. */
  export let chart: LineChart | null = null;

  // Assigned by Svelte's bind:this directive.
  // oxlint-disable-next-line no-unassigned-vars
  let canvas: HTMLCanvasElement;
  let ready = false;
  let readyNotified = false;
  let disposed = false;
  let rendererFailed = false;
  let reportedRendererError: unknown;
  let appliedData: LineData | undefined;
  let appliedAppearance: DeepPartial<LineAppearanceOptions> | undefined;
  let appliedViewport: Partial<Viewport> | undefined;

  // The arguments are the reactive dependencies; the body reads them directly
  // so a single change installs data, appearance, and viewport in one update.
  $: applyReactiveProps(ready, chart, data, appearance, viewport, viewportAnimated);
  $: if (chart) {
    chart.setStatsCallback(onStats ? (stats) => onStats?.(stats) : null, {
      intervalMs: statsIntervalMs,
    });
  }

  // Each dataset object is applied at most once. Worker mode transfers its
  // buffers; identity tracking also prevents duplicate installs in main-thread
  // mode.
  function applyReactiveProps(
    isReady: boolean,
    instance: LineChart | null,
    nextData: LineData | undefined,
    nextAppearance: DeepPartial<LineAppearanceOptions> | undefined,
    nextViewport: Partial<Viewport> | undefined,
    animated: boolean | undefined,
  ): void {
    if (!isReady || !instance || disposed || rendererFailed) return;
    try {
      instance.batch(() => {
        if (nextData && nextData !== appliedData) {
          installLineData(instance, nextData, dataUpdateOptions);
          appliedData = nextData;
        }
        if (nextAppearance && nextAppearance !== appliedAppearance) {
          instance.updateAppearance(nextAppearance);
          appliedAppearance = nextAppearance;
        }
        if (hasViewport(nextViewport) && nextViewport !== appliedViewport) {
          instance.setViewport(nextViewport, { animated });
          appliedViewport = nextViewport;
        }
      });
    } catch (error) {
      if (!disposed && error !== reportedRendererError) onError?.(error);
      return;
    }
    if (!disposed && !rendererFailed && chart === instance && !readyNotified) {
      readyNotified = true;
      try {
        onReady?.(instance);
      } catch (error) {
        if (!disposed) onError?.(error);
      }
    }
  }

  onMount(() => {
    let instance: LineChart;
    try {
      instance = new LineChart(canvas, options);
    } catch (error) {
      if (!disposed) onError?.(error);
      return;
    }
    chart = instance;
    instance.setRendererErrorCallback((error) => {
      rendererFailed = true;
      reportedRendererError = error;
      if (!disposed) onError?.(error);
    });
    instance.setOverlayErrorCallback((error) => {
      if (!disposed) onError?.(error);
    });
    instance.setSeriesVisibilityCallback((event) => onSeriesVisibilityChange?.(event));
    void instance
      .initialize()
      .then(() => {
        if (disposed || chart !== instance) return;
        // The reactive pass installs props before notifying readiness and can
        // retry with corrected props if the initial installation fails.
        ready = true;
      })
      .catch((error) => {
        if (!disposed && error !== reportedRendererError) onError?.(error);
      });
    return () => {
      disposed = true;
      ready = false;
      instance.destroy();
      if (chart === instance) chart = null;
    };
  });
</script>

<canvas
  bind:this={canvas}
  class={canvasClass}
  style={`display:block;width:100%;height:100%;${canvasStyle}`}
  aria-label={ariaLabel ?? (options.interactive === false ? "Chart" : "Interactive chart")}
  aria-describedby={ariaDescribedBy}
  role={canvasRole ?? (options.interactive === false ? "img" : "application")}
  tabindex={canvasTabIndex ?? (options.interactive === false ? undefined : 0)}
></canvas>
